version: '3.8'
services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_DB=dwallet
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5433:5432'
  backend:
    image: node:latest
    working_dir: "/var/backend"
    volumes:
      - "./digital_wallet_backend/:/var/backend"
    ports:
      - '3001:3001'
    links:
      - postgres      
    command: [ "sh", "-c", "npm install; npm run typeorm:run-migrations; npm start"]
    depends_on: 
      - postgres
    environment:
      PORT: 3001
      BASE_URL: http://backend:3001
      DATABASE_HOST: postgres
      DATABASE_NAME: dwallet
      DATABASE_USER: db_user
      DATABASE_PASSWORD: db_password
      DATABASE_PORT: 5432
      DATABASE_SCHEMA: public
      DATABASE_SYNC: "false"
      DATABASE_RUN_MIGRATIONS: "true"
      DATABASE_MIGRATIONS_TABLE_NAME: migrations
      ETHERSCAN_API_KEY: NSZCD6S4TKVWRS13PMQFMVTNP6H7NAGHUY
  frontend:
    image: node:latest
    working_dir: "/var/frontend"
    volumes:
      - "./digital_wallet_frontend/:/var/frontend"
    ports:
      - '3000:3000'
    links:
      - postgres      
    command: [ "sh", "-c", "npm install; npm run build; npm start"]
    depends_on: 
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001/walletAPI
volumes:
  postgres: